<?php

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

function fluent_field_definitions_test_entity_base_field_info(EntityTypeInterface $entityType): array
{
    $fields = [];

    if(\Drupal::state()->get('fluent_field_definitions_test.entity_type_id') !== $entityType->id()) {
        return $fields;
    }

    /** @var BaseFieldDefinition[] $fields */
    $installField = \Drupal::state()->get('fluent_field_definitions_test.field_to_install');

    if ($installField === null) {
        return $fields;
    }

    $field = unserialize($installField);

    if ($field instanceof BaseFieldDefinition) {
        $fields[$field->getName()] = $field;
    }

    return $fields;
}
